// <auto-generated />
using Foody.Services.ProductApi.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Foody.Services.ProductApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240128105601_SeededProducts")]
    partial class SeededProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Foody.Services.ProductApi.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Appetizer",
                            Description = "Our Shawarma, prepared to perfection, is an irresistible blend of flavors and textures. Elevate your taste buds with our signature sauces, crisp vegetables, and delightful condiments.",
                            ImageUrl = "https://dotnetmastery.blob.core.windows.net/mango/12.jpg",
                            Name = "Shawarma",
                            Price = 15.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Appetizer",
                            Description = "Indulge in the rich flavors of our Chicken Palak — a culinary masterpiece that combines tender chicken with a luscious spinach-based curry. Immerse your taste buds in a symphony of aromatic spices and wholesome ingredients, creating a dining experience that's both delicious and nutritious.",
                            ImageUrl = "https://dotnetmastery.blob.core.windows.net/mango/14.jpg",
                            Name = "Chiken Palakash",
                            Price = 13.99
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Dessert",
                            Description = "Satisfy your sweet cravings with our delectable Sweet Pie, a delightful treat. Each slice is a journey into sweetness, with a perfect balance of textures and a hint of homemade goodness.",
                            ImageUrl = "https://dotnetmastery.blob.core.windows.net/mango/11.jpg",
                            Name = "Sweet Pie",
                            Price = 10.99
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Entree",
                            Description = "Experience the golden sweetness of our Honey Pie, a delectable creation that combines the richness of honey with a flaky, buttery crust.",
                            ImageUrl = "https://dotnetmastery.blob.core.windows.net/mango/13.jpg",
                            Name = "Honey Pie",
                            Price = 15.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
